name: virtual_sketch_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  mobx_codegen: ^2.0.7
  image: ^3.2.2
  image_gallery_saver: ^1.7.1
  flutter_modular: ^5.0.3
  google_fonts: ^3.0.1
  vector_math: ^2.1.2
  dio: ^4.0.6
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  flutter_native_splash: ^2.2.8
  font_awesome_flutter: ^10.1.0
  fluttertoast: ^8.1.1
  indexed: ^0.0.8
  screenshot: ^1.2.3
  arcore_flutter_plugin:
    git: https://github.com/VirtualSketch/arcore_flutter_plugin.git
  vs_ai_vision:
    git:
      url: https://github.com/VirtualSketch/vs-ai-vision.git
      ref: develop

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter_native_splash:
  image: assets/splash.png
  color: "#7A44EC"

flutter:
  uses-material-design: true
  assets:
    - assets/graph.png
