name: virtual_sketch_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  mobx_codegen: ^2.0.7
  flutter_modular: ^5.0.3
  google_fonts: ^3.0.1
  vector_math: ^2.1.2
  dio: ^4.0.6
  json_annotation: ^4.6.0
  arcore_flutter_plugin:
    git: https://github.com/VirtualSketch/arcore_flutter_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
